= MyMovies

:numbered!:
:imagesdir: images

## System dependencies

1. The app uses the Movie Database API,
https://www.themoviedb.org/documentation/api[Movie & TV API Overview]
and a the Ruby https://github.com/ahmetabdi/themoviedb[themoviedb]
gem, a wrapper for the http://docs.themoviedb.apiary.io[The Movie Database API].

2. Use the official Sass port of Bootstrap:
* https://github.com/twbs/bootstrap-sass[bootstrap-sass] –
  see README for instructions how to use it with Rails


## Configuration

The app uses the API key. To register for an API key,
https://www.themoviedb.org/login[head into your account page on TMDb] and
generate a new key from within the “API” section found in the left hand sidebar
(click *API>Details*).

Try some request from
http://docs.themoviedb.apiary.io[the Movie Database API on the Apiary console].


## How to run the test suite

TODO: RSpec documentation:

* https://github.com/rspec/rspec-rails[rspec-rails]
* https://github.com/rspec/rspec-collection_matchers[rspec-collection_matchers]
* https://github.com/rspec/rspec-expectations[rspec-expectations]

## Other things you may want to cover

This README would normally document whatever steps are necessary to get the
application up and running:

* link:.ruby-version[Ruby version]
* Database creation – do not apply here
* Database initialization – do not apply here
* Services (job queues, cache servers, search engines, etc.)
* Deployment instructions
* ...
