= MyMovies

:numbered!:
:imagesdir: images

[NOTE]
There are many API in the wild.
https://gist.github.com/wbzyl/2bd9f10f0d51f34f9bde[This gist] list many API
which that require no server-side auth or private credentials, and are
thus good for small browser-only JS projects.

This version implements `home#index`, `search#index`, and `movies#show`:
[source,console]
----
rails g controller home index
rails g controller search index
rails g controller movies show

rake routes
Prefix Verb URI Pattern      Controller#Action
search     GET  /search      search#index
movie      GET  /movies/:id  movies#show
home_index GET  /home/index  home#index
root       GET  /            home#index
----

These routes are set in _config/routes.rb_:
[source,ruby]
----
Rails.application.routes.draw do
  # get 'home/index'
  get "search", to: "search#index"
  resources :movies, only: :show
  root 'home#index'
----

## Configuration

The app uses the API key. To register for an API key,
https://www.themoviedb.org/login[head into your account page on TMDb] and
generate a new key from within the “API” section found in the left hand sidebar
(click *API>Details*).

[NOTE]
Try some request from
http://docs.themoviedb.apiary.io[the Movie Database API on the Apiary console].

Add initializer _set_tmdb_api_key.rb_:

[source,ruby]
.config/initializers/set_tmdb_api_key.rb
----
tmdb_api_key = ENV['TMDB_API_KEY']
if tmdb_api_key.nil?
  puts "Please set your MovieDB key with"
  puts "$ export TMDB_API_KEY=YOUR_TMDb_KEY"
  puts "or get/generate new key within API > Details section"
  puts "on your acount TMDb page https://www.themoviedb.org/login"
else
puts "TMDB API KEY: #{tmdb_api_key}"
end
Tmdb::Api.key(tmdb_api_key)
Tmdb::Api.language("en")  # optionally, set your default language
----

Set the api key in the environment wit:
[source,console]
----
export TMDB_API_KEY=REPLACE_THIS_WITH_YOUR_KEY
----
and check with _bin/tmdb_ script if the TMDb API works:
[source,console]
----
bin/tmdb
----


## System dependencies

1. The Movie Database API:
* https://www.themoviedb.org/documentation/api[Movie & TV API Overview]
* the Ruby https://github.com/ahmetabdi/themoviedb[themoviedb]
  gem, a wrapper for the http://docs.themoviedb.apiary.io[The Movie Database API].

2. Use the official Sass port of Bootstrap:
* https://github.com/twbs/bootstrap-sass[bootstrap-sass] –
  see README for instructions how to use it with Rails
* Integrating Rails and Bootstrap:
** http://www.gotealeaf.com/blog/integrating-rails-and-bootstrap-part-1[Part 1 - the Installation]
** http://www.gotealeaf.com/blog/integrating-rails-and-bootstrap-part-2/[Part 2 - CSS and Components]


## How to run the test suite

Useful links to the RSpec documentation:

* https://github.com/rspec/rspec-rails[rspec-rails]
* https://github.com/rspec/rspec-collection_matchers[rspec-collection_matchers]
* https://github.com/rspec/rspec-expectations[rspec-expectations]

Useful links to the Minitest documentation:
* https://github.com/blowmage/minitest-rails/tree/1.x#readme[minitest-rails] –
  install howto
* https://github.com/seattlerb/minitest[minitest] – sources on GitHub
* http://docs.seattlerb.org/minitest[minitest/{unit,spec,mock,benchmark}]
* https://github.com/blowmage/minitest-rails-capybara[minitest-rails-capybara] –
  Capybara integration for _MiniTest::Rails_
* http://blowmage.com/minitest-rails-capybara[minitest-rails-capybara]


## Other things you may want to cover

This README would normally document whatever steps are necessary to get the
application up and running:

* link:.ruby-version[Ruby version]
* Database creation – do not apply here
* Database initialization – do not apply here
* Services (job queues, cache servers, search engines, etc.)
* Deployment instructions – Heroku?
